site:
  url: https://tap-cloudflare.pages.dev
  title: My cool site
  template_base: page
  template_styles:
    home:
    - file: base.css
      inline: true
    article:
    - file: base.css
      inline: true
    - file: article.css
      inline: false
    notes:
    - file: base.css
      inline: true
    - file: notes.css
      inline: false

functions:
  - path: /notes
    template: notes
    secret_name_tap_url: TAP_URL_1
    secret_name_tap_key: TAP_KEY_1

pages:
  - path: /
    template: home
    props:
      meta:title: Home
      meta:description: Very cool homepage

  - path: /404.html
    template: not-found
    props:
      meta:title: Home
      meta:description: Very cool homepage

  - path: /article/example
    template: article
    markdown:
      body: example.md
    props:
      meta:title: Article Title
      meta:description: Very cool homepage
      title: Article Title
      subtitle: A Very Neat Article